### ISSUE TITLE
file log_program.ado not found

### ISSUE THREAD

**Issue by JarnoKATurunen** [dballaelliott/esplot#3]
I tried to use esplot for my data:

1. Installation was done via Stata: 
net install esplot, from("https://raw.githubusercontent.com/dballaelliott/esplot/pkg/") replace

(When trying to use the esplot -command, I encountered the "file log_program.ado not found"

2. I downloaded the files direct from https://github.com/dballaelliott/esplot and installed them to ado-folder ... 

I encountered the "file log_program.ado not found" again. 

I don't know whether the problem is in esplot -package or in my Stata. 

Has anyone encountered this problem? Any solutions available?

**Comment by dballaelliott** [comment]
`log_program` is a custom do file that we use in development. That dependency should not exist in the main `pkg` branch; I’ll patch that soon.

**Comment by dballaelliott** [comment]
I believe I've dealt with this dependency in the `pkg` branch. 

Please try reinstalling with 
`net install esplot, from("https://raw.githubusercontent.com/dballaelliott/esplot/pkg/") replace`

**Comment by JarnoKATurunen** [comment]
Thank you!

I already faced the next problem with esplot in form of “ variable b_0 not found “.

I at least thought I have done everything according to examples. (And I tried three different data of mine.) (And since there are no examples using available online data, I’m not sure if the fault is indeed in my data or the program.)

**Comment by dballaelliott** [comment]
Thanks Jarno,

I haven't seen this bug before. Can you try these steps and upload the
resulting `debug_esplot.log` file to help me debug?

```
set trace on
log using debug_esplot.log

<your command>
log close
```

I'll also see what I can do with respect to an example with public data
(the program was developed for a project that used confidential data).

Best,
Dylan

**Comment by dballaelliott** [comment]
Thanks Jarno,

I haven't seen this bug before. Can you try these steps and upload the
resulting `debug_esplot.log` file to help me debug?

```
set trace on
log using debug_esplot.log

<your command>
log close
```

I'll also see what I can do with respect to an example with public data
(the program was developed for a project that used confidential data).

Best,
Dylan

**Comment by dballaelliott** [comment]
I've added an examples folder to the master that can be directly downloaded. `make_examples.do` should run as is on the provided sample data, which should have the same variable names as the examples on the [vignette](https://dballaelliott.github.io/esplot). The values have been randomized so the output will be different.

**Comment by JarnoKATurunen** [comment]
> Thanks Jarno,
> 
> I haven't seen this bug before. Can you try these steps and upload the
> resulting `debug_esplot.log` file to help me debug?
> 
> ```
> set trace on
> log using debug_esplot.log
> 
> <your command>
> log close
> ```
> 
> I'll also see what I can do with respect to an example with public data
> (the program was developed for a project that used confidential data).
> 
> Best,
> Dylan

I attached the debug-file. I used the example.csv -data. Each esplot command seem to result in error "variable b_1 not found".
[debug_esplot.zip](https://github.com/dballaelliott/esplot/files/4464141/debug_esplot.zip)

-Jarno

**Comment by dballaelliott** [comment]
Thanks for attaching. This is strange; I pulled and ran the file on a different laptop (running stata 14.2) and it ran without throwing that error. 

Your log file was very helpful, it looks like `esplot` was throwing an error when it tried to use a variable abbreviation. I wonder if there are Stata settings or differences across versions with respect to how it handles variable abbreviation (i.e. using `foo` to refer to `foobar`).  Out of curiosity which version of Stata are you using?

I've pushed a fix to `pkg` but if the error persists, kindly upload the updated logs and I'll take a look. 

-Dylan

**Comment by JarnoKATurunen** [comment]
>  Out of curiosity which version of Stata are you using?
> 


I'm using Stata 15.1.

I also made sure to test your data  from different disks (due to company restrictions on writing to C: -disk; I'm using employer pc), but it had no effect. 
I'll test the new pkg and get back to you tomorrow. Thanks!

**Comment by JarnoKATurunen** [comment]
Took a few days to test, but still getting the error 

[debug_esplot160420.zip](https://github.com/dballaelliott/esplot/files/4488895/debug_esplot160420.zip)


-Jarno

**Comment by dballaelliott** [comment]
Hi Jarno, 

I believe I've identified the cause of this error; the `varabbrev` setting. I was able to replicate this bug by typing `set varabbrev off`. This then gave me the same `variable b_1 not found` error message. Then, after typing `set varabbrev on`, I was able to run the code successfully.  

Try running the do file after `set varabbrev on`! I'll work on further debugging so that it doesn't require variable abbreviation, but it may be a few days until I get to it. 

Let me know if enabling variable abbreviation eliminates the error for you!

**Comment by JarnoKATurunen** [comment]
Thank you Dylan! 

I am able to run the code successfully now! Both, with your example data and my own data. And at least for now I have encountered zero new errors. 
I appreciate your good work on graphing event studies. Thanks again! 

Any suggestions on how to cite esplot? If I ever end up using graphs produced by it in publications? 

-jarno

**Comment by dballaelliott** [comment]
Hi Jarno, 

Glad to hear that it’s working; I hope it continues to be useful to you! 

You are free to use any plots you make in whatever capacity you’d like - this code is intended as a public good!
